name: bibletime
version: 3.0.0-beta2
summary: BibleTime
title: A Bible study tool
description: BibleTime is a powerful cross platform Bible study tool.
icon: gui/bibletime.svg
confinement: strict
grade: devel
base: core18
type: app

apps:

    bibletime:
        command: desktop-launch bibletime
        environment:
            DISABLE_WAYLAND: 1
        desktop: gui/bibletime.desktop
        plugs:
            - network
            - unity7
            - opengl
            - desktop
            - home
            - x11
            - wayland

parts:

    desktop-qt5:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-depth: 1
        source-subdir: qt

        plugin: make
        make-parameters: ["FLAVOR=qt5"]
        build-packages:
            - build-essential
            - qtbase5-dev
            - dpkg-dev
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5 # for loading icon themes which are svg
            - try: [appmenu-qt5] # not available on core18
            - locales-all
            - xdg-user-dirs
            - fcitx-frontend-qt5

    sword:
        source-type: tar
        source: http://crosswire.org/ftpmirror/pub/sword/source/v1.8/sword-1.8.1.tar.gz
        plugin: cmake
        configflags: 
            - -DSWORD_NO_ICU=No 
        build-packages:
            - g++
            - libcurl4-openssl-dev
            - libclucene-dev
        stage-packages:
            - libcurl4
            - libclucene-contribs1v5
            - libclucene-core1v5

    bibletime:
        source: https://github.com/bibletime/bibletime/releases/download/v3.0_beta2/bibletime-3.0_beta2.tar.xz
        plugin: cmake
        configflags: [-DCMAKE_BUILD_TYPE=Release]
        build-packages:
            - qtchooser
            - qttools5-dev
            - qttools5-dev-tools
            - g++
            - qtbase5-dev
            - qtbase5-dev-tools
            - libqt5svg5-dev
            - qt5-qmake
            - qtdeclarative5-dev
            - libqt5x11extras5-dev
        stage-packages:
            - libcurl4
            - libclucene-contribs1v5
            - libclucene-core1v5
            - libqt5core5a
            - libqt5gui5
            - libqt5svg5
            - libqt5printsupport5
            - libqt5quickwidgets5
            - libqt5xml5
            - libqt5quick5
            - libqt5quickcontrols2-5
            - libqt5x11extras5
            - libqt5qml5
            - libgtk2.0-0
            - mesa-utils
            - mesa-utils-extra
            - qtwayland5
            - qt5dxcb-plugin
            - qml-module-qtquick2
            - qml-module-qtquick-dialogs
            - qml-module-qtquick-privatewidgets
            - qml-module-qtquick-controls
            - qml-module-qtquick-controls2
            - qtdeclarative5-qtquick2-plugin
            - qmlscene
        after: [sword,desktop-qt5]

    extra-desktop-files:
        plugin: dump
        source: gui
        organize:
            '*.desktop': gui/   
            '*.svg': gui/   
