name: bibletime
version: 3.1.0
summary: BibleTime
title: A Bible study tool
description: BibleTime is a powerful cross platform Bible study tool.
confinement: strict
grade: stable
base: core24
icon: gui/bibletime.svg
type: app

apps:
    bibletime:
        command: usr/bin/bibletime
        desktop: gui/bibletime.desktop
        extensions:
            - kde-neon-6
        plugs:
            - unity7
            - desktop
            - home
            - x11
            - wayland

parts:
    bibletime-docs:
        source: https://github.com/bibletime/generated_docs.git
        source-type: git
        plugin: nil
        override-stage: |
            mkdir -p $SNAPCRAFT_STAGE/usr/share/doc/bibletime
            cp -r ${SNAPCRAFT_PART_SRC}/docs/v3.1.0/* $SNAPCRAFT_STAGE/usr/share/doc/bibletime
        override-prime: |
            mkdir -p $SNAPCRAFT_PRIME/usr/share/doc/bibletime
            cp -r ${SNAPCRAFT_PART_SRC}/docs/v3.1.0/* $SNAPCRAFT_PRIME/usr/share/doc/bibletime
        after: [bibletime]

    bibletime:
        source: https://github.com/bibletime/bibletime/archive/v3.1.0.zip
        source-type: zip
        override-pull: |
            snapcraftctl pull
            cd bibletime-3.1.0
            pwd
        plugin: cmake
        source-subdir: bibletime-3.1.0
        cmake-parameters: [
            "-DUSE_QT6=ON",
            "-DCMAKE_INSTALL_PREFIX=/usr",
            "-DFindSword_LIBS=${SNAPCRAFT_STAGE}/usr/lib/sword.lib",
            "-DFindSword_INCS=${SNAPCRAFT_STAGE}/usr/include",
            "-DCMAKE_BUILD_TYPE=Release",
            "-DBT_RUNTIME_DOCDIR=share/doc/bibletime",
            "-DBUILD_HANDBOOK_HTML=OFF",
            "-DBUILD_HANDBOOK_PDF=OFF",
            "-DBUILD_HOWTO_HTML=OFF",
            "-DBUILD_HOWTO_PDF=OFF" 
        ]
        build-packages:
            - libsword-dev
            - libclucene-dev
            - libproxy1v5
        stage-packages:
            - libxkbcommon0
            - xkb-data
            - libclucene-core1v5
            - libsword1.9.0t64
        after: [extra-desktop-files]

    extra-desktop-files:
        plugin: dump
        source: gui
        organize:
            '*.desktop': gui/   
            '*.svg': gui/   

lint:
  ignore:
    - classic
    - library:
      - usr/lib/x86_64-linux-gnu/libicuio.so.74.2
      - usr/lib/x86_64-linux-gnu/libicutest.so.74.2
      - usr/lib/x86_64-linux-gnu/libicutu.so.74.2
